name: selenium_homework_test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  full_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f selenium-homework/requirements.txt ]; then pip install -r selenium-homework/requirements.txt; fi

      - name: Builds and Starts
        run: |
          docker-compose up -d

      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable

      - name: Test with pytest - locators
        run: |
              pytest selenium-homework/locators.py

      - name: Test with pytest - elementtype
        run: |
              pytest selenium-homework/elementtype.py
